### ISSUE TITLE
[improvement] ReadableStream also need to have .pipe() method

### ISSUE THREAD

**Issue by ghost** [ahlwong/dakota-cassandra#3]
For example HighlandJS relies on it:
https://github.com/caolan/highland/blob/master/lib/index.js#L642

Cassandra driver also provides .pipe (implicitly):
https://github.com/datastax/nodejs-driver/blob/bc4ad0dee07b414441a67881d49b9f8d26058d73/lib/types/result-stream.js#L14

Official NodeJS docs:
https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options

**Comment by ghost** [comment]
I use this hack:

``` javascript
WrappedStream.prototype.pipe = function(destination, options) {
  var self = this;
  this.on('readable', function() {
    var model;
    while (model = self.read()) {
      destination.write(model);
    }
  })
};
```

**Comment by ahlwong** [comment]
I committed a fix that adds .pipe to WrappedStream. Please let me know if this solves the issue.

**Comment by ghost** [comment]
You actually bypassing WrappedStream.prototype.read(). Destination stream will get Row instances directly from cass driver. If user are fetching results from pipe (just like Highland does) this will lead to #2. That's why i used my hack above. Maybe my case is 1% from all cases and this isn't a big deal.

**Comment by ahlwong** [comment]
Can you take a look and confirm .pipe is working as expected now? I overrode .add method on Cassandra's stream so objects in the stream should be model instances at insertion, instead of being dynamically created when the stream is read.

**Comment by ghost** [comment]
Sorry, i was busy a bit. I'll test it ASAP.

**Comment by ghost** [comment]
I checked this one today. Seems like all ok.
