### ISSUE TITLE
[bug] Wrong arguments order causes model always to be null

### ISSUE THREAD

**Issue by ghost** [ahlwong/dakota-cassandra#4]
https://github.com/ahlwong/dakota-cassandra/blob/873c858c31ebec9fb8d0d6c5f691a9518eaf167d/lib/model.js#L1456

**Comment by ahlwong** [comment]
Good catch!

Fixed here:
https://github.com/ahlwong/dakota-cassandra/commit/a8fa5a14e738953a9554bf4a05c36f3f8e04f210
