### ISSUE TITLE
error with example options

### ISSUE THREAD

**Issue by davidmessem** [ahlwong/dakota-cassandra#7]
I cannot run dakota-cassandra. I get the following error when running with default options

```
dakota.error.dakota.InvalidArgument: Argument should be a {}. 
```

Below is my js file:

```
var Dakota = require("dakota-cassandra")

var options = {
  connection: {
    contactPoints: [
      '127.0.0.1'
    ],
    keyspace: 'dakota_test'
  },
  keyspace: {
    replication: { 'class': 'SimpleStrategy', 'replication_factor': 1 },
    durableWrites: true
  }
};

var dakota = new Dakota(options);
```

**Comment by ahlwong** [comment]
Hi, please pass an empty object as the second argument to new Dakota for the time being. I believe the code is expecting userDefinedTypes to be defined but is not seeing the argument.

I will commit a fix for the documentation or to the driver shortly.

**Comment by ahlwong** [comment]
https://github.com/ahlwong/dakota-cassandra/commit/7a3b7c5a228135830b4437f0e549254af8d5ed89

**Comment by davidmessem** [comment]
Thank you for the quick response @ahlwong , that worked :+1:
